---

- name: Get Optimal oVirt Storage Domain
  get_storage_domain:
    engine_url: "{{ engine_url }}"
    engine_user: "{{ engine_user }}"
    engine_password: "{{ engine_password }}"
    engine_cafile: "{{ engine_cafile }}"
    cluster: "{{ cluster }}"
    blacklisted_domains: "{{ blacklisted_domains }}"
  register: ovirt_storage_domain
  delegate_to: localhost
  tags:
    - ovirt
    - storage

- name: Display the oVirt Storage Domain
  debug:
    msg: "oVirt storage domain: {{ ovirt_storage_domain }}"
  tags:
    - ovirt
    - storage
